version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven..."
      - curl -sSL "https://apache.osuosl.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz" -o apache-maven.tar.gz
      - tar xzf apache-maven.tar.gz
      - export PATH="$PWD/apache-maven-3.8.4/bin:$PATH"

  pre_build:
    commands:
      - REPOSITORY_URI=003048939092.dkr.ecr.eu-north-1.amazonaws.com/privatedocker
      - echo "Logging in to AWS ECR"
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - git clone --branch master --single-branch --depth 1 https://git-codecommit.eu-north-1.amazonaws.com/v1/repos/AWS-File-Hosting

  build:
    commands:
      - echo "Building the project..."
      - mvn test-compile
      - echo "Running tests..."
      - mvn surefire:test
      - find ./target/surefire-reports -name "*.xml" | xargs junitreport --format junit --output-dir reports || true
      - echo "Docker build and push..."
      - REPOSITORY_URI=public.ecr.aws/j0p0p7e9/publicrepo
      - echo "Logging in to AWS ECR"
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - docker build -t $REPOSITORY_URI:latest .
      - docker push $REPOSITORY_URI --all-tags

  post_build:
    commands:
      - echo "Pushing the Docker images..."
      - docker push $REPOSITORY_URI:latest
