version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  Clean:
    commands:
      - echo "Running Maven clean..."
      - mvn clean

  Test:
    commands:
      - echo "Running tests..."
      - mvn surefire:test
      - echo "Finished test"

  Deploy:
    commands:
      - echo "Creating .war..."
      - mvn war:war
      - echo "ROOT.war is ready to be used"
      - mv target/ROOT.war arn:aws:s3:::deploybucket88
