version: 0.2

phases:
  pre_build:
    commands:
      - REPOSITORY_URI=003048939092.dkr.ecr.eu-north-1.amazonaws.com/privatedocker
      - echo "Loggin in to AWS ECR"
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin $REPOSITORY_URI

      - echo "Building the project..."
      - mvn clean

  build:
    commands:
      - echo "Running tests..."
      - mvn surefire:test
      - echo "Finished test"

  post_build:
    commands:
       - echo "Creating .war..."
       - mvn war:war
       - echo "ROOT.war is ready to be used"
       -  mv target/ROOT.war arn:aws:s3:::deploybucket88
       - echo "building dock"
       - docker build -t privatedocker .
       - docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$(date +'%Y%m%d-%H%M') .
       - docker push $REPOSITORY_URI --all-tags
