version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - REPOSITORY_URI=public.ecr.aws/j0p0p7e9/publicrepo
      - echo "Loggin in to AWS ECR"
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin   $REPOSITORY_URI

      - echo "Building the project..."
      - mvn clean

  build:
    commands:
      - echo "Running tests..."
      - mvn surefire:test
      - echo "Finished test"

  post_build:
    commands:
       - echo "Creating .war..."
       - mvn war:war
       - echo "ROOT.war is ready to be used"
       -  mv target/ROOT.war arn:aws:s3:::deploybucket88
       -
       - echo "building dockerfile"
       - docker build -t publicrepo:latest .
       - docker tag publicrepo:latest public.ecr.aws/j0p0p7e9/publicrepo:latest
       - docker push public.ecr.aws/j0p0p7e9/publicrepo:latest

