version: 0.2
phases:
  pre_build:
    commands:
      - REPOSITORY_URI=public.ecr.aws/j0p0p7e9/publicrepo
      - echo "Loggin in to AWS ECR"
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/j0p0p7e9 $REPOSITORY_URI

  build:
    commands:
      - docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$(date +'%Y%m%d-%H%M') .
      - docker push $REPOSITORY_URI --all-tags
