version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Building the project..."
      - mvn clean

  build:
    commands:
      - echo "Running tests..."
      - mvn surefire:test
      - echo "Packaging the project..."
      - mvn package

  post_build:
    commands:
      - echo "Deploying the project..."
