version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Building the project..."
      - mvn clean

  build:
    commands:
      - echo "Running tests..."
      - mvn surefire:test
      - echo "Finished test"

  post_build:
    commands:
       - echo "Creating .war..."
       - mvn war:war
       - echo "ROOT.war is ready to be used"
       -  mv target/ROOT.war arn:aws:s3:::deploybucket88

