version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - apt-get install -y maven

  pre_build:
    commands:
      - echo "Cloning the repository..."
      - git clone --branch master --single-branch --depth 1 https://git-codecommit.eu-north-1.amazonaws.com/v1/repos/AWS-File-Hosting
      - echo "Cleaning the project..."
      - mvn clean

  build:
    commands:
      - echo "Building the project..."
      - mvn test-compile

  test:
    commands:
      - echo "Running tests..."
      - mvn surefire:test
      - find ./target/surefire-reports -name "*.xml" | xargs junitreport --format junit --output-dir reports || true

  post_build:
    commands:
      - echo "Packaging the project..."
      - mvn war:war
