version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  Clean:
    commands:
      - echo "running maven clean."
      - mvn clean



  Test:
    commands:
      - echo "Running tests..."
      - mvn surefire:test
      -  echo 'finished test'

  Deploy:
    commands:
      - echo "creating .war..."
      - war:war
      - echo "ROOT.war ready to be used"


    }


