version: 0.2

phases:
  pre_build:
    commands:
      - REPOSITORY_URI=public.ecr.aws/j0p0p7e9/publicrepo
      - echo "Loggin in to AWS ECR"
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin   $REPOSITORY_URI

      - echo "Building the project..."
      - mvn clean

  build:
    commands:
      - echo "Running tests..."
      - mvn surefire:test
      - echo "Finished test"

      - echo "Creating .jar..."
      - mvn jar:jar
      - echo "ROOT.jar is ready to be used"

      - docker build -t publicrepo .
      - docker tag publicrepo:latest public.ecr.aws/j0p0p7e9/publicrepo:latest
  post_build:
      commands:
       - docker push $REPOSITORY_URI:latest
#       - docker push public.ecr.aws/j0p0p7e9/publicrepo:latest
artifacts:
  file: imagedefinitions.json
